// TypeScript mirror of /workspace/junoreality/contracts/cw-reality/src/state.rs +
// msg.rs. Schemas are generated by `cargo run --example schema` into
// /workspace/junoreality/contracts/cw-reality/schema/cw-reality.json — these
// types are the hand-curated, ergonomic subset the UI actually uses.

export type AnswerType = 'bool' | 'uint' | 'string' | 'bytes'

export type State =
  | 'not_created'
  | 'open_unanswered'
  | 'open_answered'
  | 'pending_arbitration'
  | 'finalized'
  | 'claimed'

export interface AnswerSchemaFilter {
  contract: string
  filter: unknown
}

export interface Question {
  asker: string
  text: string
  answer_type: AnswerType
  bond_denom: string
  initial_bond: string
  min_bond: string
  answer_timeout_secs: number
  arbitrator: string | null
  arbitration_timeout_secs: number
  arbitration_deadline: number | null
  answer_schema: AnswerSchemaFilter | null
  nonce: number
  opening_ts: number | null
  bounty: string
  best_answer: string | null
  current_bond: string
  history_hash: number[]
  round_count: number
  finalize_ts: number | null
  is_pending_arbitration: boolean
  is_claimed: boolean
}

export interface QuestionResponse {
  question_id: string // base64-encoded 32-byte ID
  question: Question
  state: State
}

export interface QuestionsListResponse {
  questions: QuestionResponse[]
}

export interface FinalAnswerResponse {
  question_id: string
  final_answer: string
  final_bond: string
}

export interface BalanceResponse {
  address: string
  denom: string
  amount: string
}

export interface ConfigResponse {
  admin: string | null
  min_initial_bond_floor: string
  min_answer_timeout_secs: number
}

export interface HistoryEntry {
  prev_hash: string // base64
  answer: string // base64
  bond_amount: string
  answerer: string
  is_commitment: boolean
}
